version: '2.1'
orbs:
  gh: circleci/github-cli@2.0
jobs:
  create-a-pr:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - gh/setup
      - run:
          command: |
            gh pr create --title "Bugfix from $CIRCLE_BRANCH"
          name: Create Pull Request
      - gh/clone
workflows:
  use-my-orb:
    jobs:
      - create-a-pr
